### ISSUE TITLE
pathways have unconnected lines: caused by converter or in original Reactome version?

### ISSUE THREAD

**Issue by egonw** [wikipathways/reactome2gpml-converter#52]
a clear from this recent curation event in [WP4082](https://www.wikipathways.org/index.php/Pathway:WP4082):

![image](https://user-images.githubusercontent.com/26721/39956760-1000f852-55e7-11e8-962c-c0d706a1a992.png)

**Comment by DeniseSl22** [comment]
I told students not to bother with Reactome PWs; next time I'll filter them out of the lists I make for the curation events (and Tina said the bot to adds these tags should be adapted as well). Since the Reactome structure is different, the lines are actually not unconnected, but appear to be so (all lines get anchors, and when you connect a line(1) to an anchor of another line(2), the end of that line(2) is "unconnected"). So, this is actually intentional.
